name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: npm ci
    - name: Lint Project
      run: npm run lint
    - name: Run Tests
      run: npm test
    - name: Build
      run: npm run build
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: startsWith(github.ref, 'refs/heads/refactor')
      with:
        ACCESS_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        CLEAN: true
        FOLDER: dist
        BRANCH: gh-pages
